### ISSUE TITLE
NullPointerException 1.20.4 "this.c" is null

### ISSUE THREAD

**Issue by Bloodlex** [BreweryTeam/BreweryX#35]
Hey, I have this exception on 1.20.4:

`[17:50:17 WARN]: [BreweryX] Global task for BreweryX v3.2.7 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.PlayerConnection.b(net.minecraft.network.protocol.Packet)" because "this.c" is null
        at net.minecraft.server.level.ServerPlayer.onEffectAdded(ServerPlayer.java:2017) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1216) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1182) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1173) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:521) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:515) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.potion.PotionEffect.apply(PotionEffect.java:278) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.dre.brewery.utility.BUtil.reapplyPotionEffect(BUtil.java:176) ~[BreweryX-3.2.7.jar:?]
        at com.dre.brewery.BPlayer.hangoverEffects(BPlayer.java:795) ~[BreweryX-3.2.7.jar:?]
        at com.dre.brewery.BPlayer.login(BPlayer.java:509) ~[BreweryX-3.2.7.jar:?]
        at com.dre.brewery.BPlayer.lambda$join$4(BPlayer.java:497) ~[BreweryX-3.2.7.jar:?]
        at com.dre.brewery.depend.universalScheduler.foliaScheduler.FoliaScheduler.lambda$runTaskLater$1(FoliaScheduler.java:58) ~[BreweryX-3.2.7.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[purpur-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[purpur-1.20.4.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1682) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]`

**Comment by Jsinco** [comment]
Looks like an issue with the server? Try 1.20.2 or a different build
