### ISSUE TITLE
Plugin breaks at boot with duplicate key 

### ISSUE THREAD

**Issue by BAD7777** [BreweryTeam/BreweryX#68]
[12:39:02] [Server thread/INFO]: [BreweryX] Enabling BreweryX v3.4.3;master
[12:39:02] [Server thread/INFO]: [Напитки] Using language: ru.yml
[12:39:02] [Server thread/INFO]: [Напитки] [Recipes] Loading Recipes - vBX3.4.3 by Jsinco
[12:39:02] [Server thread/INFO]: [Напитки] [Recipes] Loaded 62 recipes from Brewery!
[12:39:02] [Server thread/INFO]: [Напитки] Loaded 1 addon(s)
[12:39:02] [Server thread/INFO]: [Напитки] Minecraft version: 1.21
[12:39:02] [Server thread/INFO]: [Напитки] DataManager created: MySQL
[12:39:03] [Server thread/ERROR]: Error occurred while enabling BreweryX v3.4.3;master (Is it up to date?)
java.lang.IllegalStateException: Duplicate key CraftBlock{pos=BlockPos{x=257, y=88, z=-7986},type=AIR,data=Block{minecraft:air},fluid=net.minecraft.world.level.material.EmptyFluid@50dc4f9c} (attempted merging values com.dre.brewery.BCauldron@2b44ba50 and com.dre.brewery.BCauldron@199ef65c)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at BreweryX-3.4.3.jar/com.dre.brewery.BreweryPlugin.onEnable(BreweryPlugin.java:169) ~[BreweryX-3.4.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:39:03] [Server thread/INFO]: [BreweryX] Disabling BreweryX v3.4.3;master
[12:39:03] [Server thread/INFO]: [Напитки] [Recipes] Recipes addon disabled.
[12:39:03] [Server thread/INFO]: [Напитки] Disabled 1 addon(s)
[12:39:03] [Server thread/INFO]: [Напитки] Closed connection from: MySQL
[12:39:03] [Server thread/INFO]: [Напитки] BreweryX disabled!

**Comment by TomLewis** [comment]
Duplicate https://github.com/BreweryTeam/BreweryX/issues/29

**Comment by potatoru** [comment]
> This is after updating 3.3.5 to 3.4.4

Same issue after update...

**Comment by potatoru** [comment]
https://github.com/BreweryTeam/BreweryX/commit/65b04f64743787ad2aebcc934f47503eaffd49f0 works

**Comment by Vutka1** [comment]
Should be fixed in version **[3.4.5](https://github.com/BreweryTeam/BreweryX/releases/tag/3.4.5)**
